spring:
  # ===============================
  # =  Database Settings
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi5
    username: taxi5
    password: taxi5
    platform: POSTGRESQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false